### PR TITLE
Mention slack channels to join in the contributor quickstart

### PR DESCRIPTION
**Pull request by swaroopch**
As discussed with @iamtrask & team in `#team_marketing` slack channel
https://openmined.slack.com/archives/C6G0ZA0HJ/p1502823797000163

Open to suggestions! I was trying to focus on "topics" as opposed to what each
project does, because I think that is redundant with the rest of the
documentation already, and this was more about getting people to
follow and join what is discussed in each channel.

### CODE REVIEW

**Comment by cereallarceny** [comment]
Hey @swaroopch - I've actually already done this in my PR: https://github.com/OpenMined/Docs/pull/35

Would we want to merge our efforts?

**Comment by iamtrask** [comment]
Yeah! Let's combine forces between both lists and pick the elements we like. Hopefully our new work on teams will help us be able to plan this collaboration pre-PR instead of post-PR. Sorry for the hassle on this one... but we're fixing it!

**Comment by cereallarceny** [comment]
All good.  I'll put in a change on my PR to update the slack channels if we want to close this one?

**Comment by swaroopch** [comment]
@cereallarceny yep, sounds good to me!

**Pull request closed without merging**
