### PR TITLE
docs($readme): change first sentance of algorithm section under workflow

### PR DESCRIPTION
**Pull request by AdamJChen**
Changed the style of the first sentence to match the previous sections. In addition, being able to choose weights based on a previous model wasn't clear to me until you read the text in the parentheses. I thought this added a bit more smoothness to the flow of the paragraph.

### CODE REVIEW

**Review by cereallarceny — APPROVED** [review]

**Review by cereallarceny — APPROVED** [review]

**Comment by cereallarceny** [comment]
@AdamJChen Mark me as an approved reviewer and I'll merge.

**Comment by AdamJChen** [comment]
@cereallarceny a little new to this. How do I mark you as an approved reviewer?

**Review by cereallarceny — APPROVED** [review]
Terrific, I approve.

**Comment by cereallarceny** [comment]
All good!  On the right side of this pull request, you can see "Reviewers" and "Assignees".  Put my name under both.

**Comment by AdamJChen** [comment]
ah ok haha. I still need a bit of help... :( There isn't a way for me to edit anything on the right of this pull request. I can't change the text under "Assignees" and there is no button. Your name is already under "Reviewers". Thanks for your patience!

**Review by anoff — APPROVED** [review]

**Comment by anoff** [comment]
Only contributors are allowed to edit reviewers/assignees. Seems like you're not allowed to write `Docs` @cereallarceny  😛

**Comment by cereallarceny** [comment]
Incredible @anoff.  It appears I've deemed myself unworthy of my newly revoked credibility.  ;)

**Comment by AdamJChen** [comment]
@anoff @cereallarceny Thanks guys! :D

**Pull request merged**
