### PR TITLE
Moved virtualbox instructions to its own file.

### PR DESCRIPTION
**Pull request by saintograph**
Separated instructions from quickstart.md.

### CODE REVIEW

**Comment by jeamick** [comment]
Hi there! 

What we can do in order for people to do demos is to create our own OpenMined's VM and people with the use of Virtual just need to download it and use it directly

In France, we have something like this about Ethereum in order to code with some softwares already installed on the VM. Here is the repo : https://github.com/asseth/assethbox

**Comment by saintograph** [comment]
Great idea @jeamick, a custom `.ova` could be available as an option.

**Comment by cereallarceny** [comment]
@winfredselwyn This looks good, but are we referencing it anywhere in the docs?  I would request that we provide a link to it somewhere rather than just assume they'll stumble upon this file.

**Review by cereallarceny — CHANGES_REQUESTED** [review]
Need a reference in another file

**Comment by iamtrask** [comment]
Going ahead and merging! I think that this document will help lots of folks - particularly those on older Windows machines which seem to struggle with OM in it's current state. Great contribution @winfredselwyn !!

**Comment by saintograph** [comment]
Awesome, thanks @iamtrask !

**Pull request merged**
