### PR TITLE
:star2: feat: readme template

### PR DESCRIPTION
**Pull request by anoff**
@swaroopch and myself tried to find the simplest common denominator among all repositories regarding documentation. We think it will be extremely valuable if all readmes follow a certain minimum set of topics to be covered - and do that in a given order.

If this goes through I'd introduce new issues to each repo. Please do provide feedback on this as it will introduce _another_ standard..

### CODE REVIEW

**Comment by ghost** [comment]
I agree with both of you

**Comment by cereallarceny** [comment]
As do I.  Good work - I'll write an approved review.

**Review by cereallarceny — APPROVED** [review]
Good work - like this strategy.

**Comment by anoff** [comment]
Just created a ton of issues to follow up on this

https://github.com/OpenMined/Capsule/issues/2
https://github.com/OpenMined/syft.js/issues/5
https://github.com/OpenMined/mine.js/issues/20
https://github.com/OpenMined/Sonar/issues/9
https://github.com/OpenMined/PySonar/issues/18
https://github.com/OpenMined/PySyft/issues/158

I think they make good `first-pr`, sadly I couldn't label in all the repos

**Pull request merged**
